FROM node:20-alpine AS builder
WORKDIR /app


COPY package*.json ./

RUN npm install -g npm@11.0.0
RUN npm install --legacy-peer-deps
COPY . .

ARG VITE_BACKEND_BASE_URL
ARG VITE_BACKEND_API_TIMEOUT
ARG VITE_BACKEND_TOKEN
ARG VITE_LINKEDIN_URL
ARG VITE_INSTAGRAM_URL
ARG VITE_TWITTER_URL
ARG VITE_LIVE_URL
ARG VITE_PBADMIN_URL
ARG VITE_CAPTCHA_TIMEOUT

ENV VITE_BACKEND_BASE_URL=${VITE_BACKEND_BASE_URL}
ENV VITE_BACKEND_API_TIMEOUT=${VITE_BACKEND_API_TIMEOUT}
ENV VITE_BACKEND_TOKEN=${VITE_BACKEND_TOKEN}
ENV VITE_LINKEDIN_URL=${VITE_LINKEDIN_URL}
ENV VITE_INSTAGRAM_URL=${VITE_INSTAGRAM_URL}
ENV VITE_TWITTER_URL=${VITE_TWITTER_URL}
ENV VITE_LIVE_URL=${VITE_LIVE_URL}
ENV VITE_PBADMIN_URL=${VITE_PBADMIN_URL}
ENV VITE_CAPTCHA_TIMEOUT=${VITE_CAPTCHA_TIMEOUT}

RUN npm run build

FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 3665
CMD ["nginx", "-g", "daemon off;"]
