server {
  listen 3665;
  server_name www.sgaurav.me;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri /index.html;
  }

  location = /404.html {
    root /usr/share/nginx/html;
  }
}
