name: portfolio ci/cd pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Installing dependencies
        run: npm install

      - name: Building the source code
        run: npm run build

      - name: Quality gate analysis
        env:
          SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_SECRET }}
          SONAR_HOST_URL: ${{ vars.SONARQUBE_HOST }}
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.host.url=${SONAR_HOST_URL}
            -Dsonar.token=${SONARQUBE_TOKEN}
            -Dsonar.qualitygate.wait=true

      - name: Preparing the image
        if: github.event_name == 'push' && (github.ref == 'refs/heads/master'||github.ref == 'refs/heads/release')
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          VITE_BACKEND_BASE_URL: ${{ secrets.VITE_BACKEND_BASE_URL }}
          VITE_BACKEND_API_TIMEOUT: ${{ secrets.VITE_BACKEND_API_TIMEOUT }}
          VITE_BACKEND_TOKEN: ${{ secrets.VITE_BACKEND_TOKEN }}
          VITE_LINKEDIN_URL: ${{ secrets.VITE_LINKEDIN_URL }}
          VITE_INSTAGRAM_URL: ${{ secrets.VITE_INSTAGRAM_URL }}
          VITE_TWITTER_URL: ${{ secrets.VITE_TWITTER_URL }}
          VITE_LIVE_URL: ${{ secrets.VITE_LIVE_URL }}
          VITE_PBADMIN_URL: ${{ secrets.VITE_PBADMIN_URL }}
          VITE_CAPTCHA_TIMEOUT: ${{ secrets.VITE_CAPTCHA_TIMEOUT }}
          VITE_APP_VERSION: ${{secrets.VITE_APP_VERSION}}
        run: |
          docker build --build-arg VITE_BACKEND_BASE_URL=${VITE_BACKEND_BASE_URL} --build-arg VITE_BACKEND_API_TIMEOUT=${VITE_BACKEND_API_TIMEOUT} --build-arg VITE_BACKEND_TOKEN=${VITE_BACKEND_TOKEN} --build-arg VITE_LINKEDIN_URL=${VITE_LINKEDIN_URL}  --build-arg VITE_INSTAGRAM_URL=${VITE_INSTAGRAM_URL} --build-arg VITE_TWITTER_URL=${VITE_TWITTER_URL} --build-arg VITE_LIVE_URL=${VITE_LIVE_URL} --build-arg VITE_PBADMIN_URL=${VITE_PBADMIN_URL} --build-arg VITE_CAPTCHA_TIMEOUT=${VITE_CAPTCHA_TIMEOUT} --build-arg VITE_APP_VERSION=${VITE_APP_VERSION} -t portfolio .
          docker tag portfolio ${DOCKER_USERNAME}/portfolio:latest

      - name: Publishing the image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_SECRET }}
        if: github.event_name == 'push' && (github.ref == 'refs/heads/master'||github.ref == 'refs/heads/release')
        run: |
          docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
          docker push ${DOCKER_USERNAME}/portfolio:latest

      - name: Deploying the code on development server
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          npm install -g caprover
          caprover deploy \
          --host ${{ secrets.CAPROVER_HOST }} \
          -p ${{ secrets.CAPROVER_PWD }} \
          --imageName ${{ secrets.DOCKER_USERNAME }}/portfolio:latest \
          --appName portfolio-dev-website

      - name: Deploying the code on production server
        if: github.event_name == 'push' && github.ref == 'refs/heads/release'
        run: |
          npm install -g caprover
          caprover deploy \
          --host ${{ secrets.CAPROVER_PROD_HOST }} \
          -p ${{ secrets.CAPROVER_PROD_PWD }} \
          --imageName ${{ secrets.DOCKER_USERNAME }}/portfolio:latest \
          --appName portfolio
